const API='https://narion-backend.onrender.com';
const T={
  hy:{buy:'Գնել',rent:'Վարձակալել',map:'Քարտեզ',why:'Ինչու Narion',login:'Մուտք',list:'Հայտարարել գույք',eyebrow:'Իրական տվյալներ · իրական գույքեր',heroTitle:'Գտեք ճիշտ գույքը՝ առանց ավելորդ զանգերի',heroSub:'Narion-ը միավորում է վաճառքի և վարձակալության գույքերը մեկ պարզ հարթակում՝ իրական լուսանկարներով, մանրամասներով և դիտման հարցմամբ։',search:'Փնտրել',searchPh:'Թաղամաս, հասցե կամ գույքի անուն',apartments:'Բնակարաններ',proofTitle:'Ավելի վստահ ընտրություն',proof1:'Քարտերում ցուցադրվում են տվյալները ուղիղ Narion-ի բազայից։',proof2:'Օբյեկտը բացվում է ամբողջական նկարագրությամբ և պատկերասրահով։',proof3:'Դիտման հարցումը ուղարկվում է անմիջապես Narion-ին։',catalog:'Կատալոգ',catalogTitle:'Գույքեր Երևանում',catalogSub:'Այստեղ չկան ցուցադրական կամ պատահական լուսանկարներ։ Ցուցադրվում են միայն Narion API-ից ստացված հրապարակված օբյեկտները։',all:'Բոլորը',newbuild:'Նորակառույց',whyTitle:'Կենտրոնացած է գործարքի վրա, ոչ թե աղմուկի',trust1t:'Մաքուր կատալոգ',trust1d:'Գլխավոր էջը սպասում է իրական API-ին և այլևս չի ցույց տալիս պատահական demo-գույքեր։',trust2t:'Ամբողջական քարտ',trust2d:'Բացեք ցանկացած գույք՝ տեսնելու լուսանկարները, գինը, մակերեսը, սենյակները, հարկը և նկարագրությունը։',trust3t:'Հաջորդ քայլը պարզ է',trust3d:'Եթե գույքը հետաքրքրեց՝ ուղարկեք դիտման հարցում։ Narion-ը կստանա այն backend-ում։',mapTitle:'Տեսեք գույքերը քարտեզի վրա',mapSub:'Քարտեզի նշումները նույնպես գալիս են նույն Narion բազայից։',sellTitle:'Ունե՞ք գույք վաճառքի կամ վարձակալության համար',sellSub:'Թողեք ձեր կոնտակտները և Narion-ը կստանա գույքի տեղադրման հարցումը անմիջապես backend-ում։',start:'Սկսել',footer:'Անշարժ գույքի տեխնոլոգիական հարթակ Հայաստանի համար։',account:'Narion հաշիվ',register:'Գրանցվել',name:'Անուն',password:'Գաղտնաբառ',sellerTitle:'Հայտարարել գույք',sellerText:'Նշեք ձեր կոնտակտները և կարճ նկարագրեք գույքը։',view:'Դիտել',request:'Դիտման հարցում',send:'Ուղարկել',phone:'Հեռախոս',message:'Հաղորդագրություն',description:'Նկարագրություն',noObjects:'Այս ֆիլտրով գույք դեռ չկա։',loadingError:'Չհաջողվեց բեռնել գույքերը։ Փորձեք թարմացնել էջը։',logout:'Դուրս գալ',sent:'Հարցումն ուղարկված է ✓',sellerSent:'Տեղադրման հարցումն ուղարկված է ✓'},
  ru:{buy:'Купить',rent:'Арендовать',map:'Карта',why:'Почему Narion',login:'Войти',list:'Разместить объект',eyebrow:'Живые данные · реальные объекты',heroTitle:'Найдите подходящий объект без лишних звонков',heroSub:'Narion собирает продажу и аренду в одном понятном сервисе — с реальными фотографиями, подробностями и заявкой на просмотр.',search:'Найти',searchPh:'Район, адрес или название объекта',apartments:'Квартиры',proofTitle:'Выбирать проще и спокойнее',proof1:'Карточки загружаются напрямую из базы Narion.',proof2:'Каждый объект открывается с полной информацией и галереей.',proof3:'Заявка на просмотр уходит прямо в Narion.',catalog:'Каталог',catalogTitle:'Недвижимость в Ереване',catalogSub:'Здесь больше нет случайных demo-фото. Показываются только опубликованные объекты из Narion API.',all:'Все',newbuild:'Новостройки',whyTitle:'Сайт ведёт к сделке, а не создаёт шум',trust1t:'Чистый каталог',trust1d:'Главная ждёт реальные данные API и не подменяет их случайными объектами.',trust2t:'Полная карточка',trust2d:'Откройте объект и увидите фото, цену, площадь, комнаты, этаж и описание.',trust3t:'Понятный следующий шаг',trust3d:'Понравился объект — отправьте заявку на просмотр. Она сохраняется в backend Narion.',mapTitle:'Смотрите объекты на карте',mapSub:'Метки на карте загружаются из той же базы Narion.',sellTitle:'Есть объект на продажу или в аренду?',sellSub:'Оставьте контакты — запрос на размещение попадёт прямо в backend Narion.',start:'Начать',footer:'Технологичная платформа недвижимости для Армении.',account:'Аккаунт Narion',register:'Регистрация',name:'Имя',password:'Пароль',sellerTitle:'Разместить объект',sellerText:'Оставьте контакты и кратко опишите объект.',view:'Смотреть',request:'Запросить просмотр',send:'Отправить',phone:'Телефон',message:'Сообщение',description:'Описание',noObjects:'По этому фильтру объектов пока нет.',loadingError:'Не удалось загрузить объекты. Обновите страницу через несколько секунд.',logout:'Выйти',sent:'Заявка отправлена ✓',sellerSent:'Запрос на размещение отправлен ✓'},
  en:{buy:'Buy',rent:'Rent',map:'Map',why:'Why Narion',login:'Log in',list:'List a property',eyebrow:'Live data · real listings',heroTitle:'Find the right property without unnecessary calls',heroSub:'Narion brings sales and rentals into one simple experience with real photos, full details and viewing requests.',search:'Search',searchPh:'District, address or property name',apartments:'Apartments',proofTitle:'A clearer way to choose',proof1:'Cards load directly from the Narion database.',proof2:'Every listing opens with full details and a gallery.',proof3:'Viewing requests go straight to Narion.',catalog:'Catalog',catalogTitle:'Property in Yerevan',catalogSub:'No random demo photos. Only published listings returned by the Narion API.',all:'All',newbuild:'New builds',whyTitle:'Built around the transaction, not the noise',trust1t:'Clean catalog',trust1d:'The homepage waits for live API data instead of showing random fallback listings.',trust2t:'Full listing view',trust2d:'Open any property to see photos, price, area, rooms, floor and description.',trust3t:'Clear next step',trust3d:'Like a property? Send a viewing request. It is stored in the Narion backend.',mapTitle:'See listings on the map',mapSub:'Map markers are loaded from the same Narion database.',sellTitle:'Have a property to sell or rent?',sellSub:'Leave your contact details and the listing request will go directly to the Narion backend.',start:'Get started',footer:'Real estate technology for Armenia.',account:'Narion account',register:'Register',name:'Name',password:'Password',sellerTitle:'List a property',sellerText:'Leave your contacts and briefly describe the property.',view:'View',request:'Request a viewing',send:'Send',phone:'Phone',message:'Message',description:'Description',noObjects:'No properties match this filter yet.',loadingError:'Could not load listings. Refresh in a few seconds.',logout:'Log out',sent:'Request sent ✓',sellerSent:'Listing request sent ✓'}
};
let lang='hy',listings=[],filter='all',query='',authMode='login',map;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const tr=k=>T[lang][k]||k;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(p){const n=Number(p.price);return Number.isFinite(n)?new Intl.NumberFormat(lang==='ru'?'ru-RU':lang==='hy'?'hy-AM':'en-US',{maximumFractionDigits:0}).format(n)+' '+(p.currency||''):''}
function titleOf(p){return p['title_'+lang]||p.title||p.title_en||p.title_ru||p.title_hy||p.address||`#${p.id}`}
function descOf(p){return p['description_'+lang]||p.description||p.description_en||p.description_ru||p.description_hy||''}
function mediaUrl(v){if(!v)return'';try{return new URL(v,API).href}catch{return''}}
function applyLang(){document.documentElement.lang=lang;$$('[data-t]').forEach(el=>el.textContent=tr(el.dataset.t));$$('[data-ph]').forEach(el=>el.placeholder=tr(el.dataset.ph));$$('.langs button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));renderListings();updateAuthUI()}
function filtered(){return listings.filter(p=>{if(filter==='sale'&&p.listing_type!=='sale')return false;if(filter==='rent'&&p.listing_type!=='rent')return false;if(filter==='primary'&&p.market_type!=='primary')return false;if(query){const hay=[titleOf(p),p.district_name,p.property_type,p.address].join(' ').toLowerCase();if(!hay.includes(query.toLowerCase()))return false}return true})}
function card(p){const img=mediaUrl(p.primary_image),specs=[p.rooms?`${p.rooms} ${lang==='ru'?'комн.':lang==='hy'?'սեն.':'rooms'}`:'',p.area_sqm?`${p.area_sqm} m²`:'',p.market_type==='primary'?tr('newbuild'):''].filter(Boolean);return `<article class="card" data-id="${p.id}"><div class="media">${img?`<img src="${esc(img)}" alt="${esc(titleOf(p))}" loading="lazy" onerror="this.remove();this.parentElement.insertAdjacentHTML('afterbegin','<div class=&quot;fallback&quot;>Narion</div>')">`:`<div class="fallback">Narion</div>`}<span class="badge">✓ Narion</span></div><div class="price">${esc(money(p))}</div><div class="loc">${esc(titleOf(p))}</div><div class="specs">${specs.map(x=>`<span>${esc(x)}</span>`).join('')}</div></article>`}
function renderListings(){const host=$('#listingHost');if(!host)return;const items=filtered();host.className='grid';host.innerHTML=items.length?items.map(card).join(''):`<div class="empty">${tr('noObjects')}</div>`;$$('.card').forEach(c=>c.onclick=()=>openProperty(c.dataset.id))}
async function loadListings(){try{const r=await fetch(`${API}/api/properties/?_=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(r.status);const data=await r.json();listings=Array.isArray(data)?data:(data.results||[]);renderListings()}catch{$('#listingHost').className='grid';$('#listingHost').innerHTML=`<div class="empty">${tr('loadingError')}</div>`}}
function fact(label,val){return val!==null&&val!==undefined&&val!==''?`<span class="fact">${esc(label)}: <b>${esc(val)}</b></span>`:''}
async function openProperty(id){const modal=$('#detailModal');modal.classList.add('open');$('#detailContent').innerHTML='<div style="padding:80px;text-align:center;color:#777">Loading…</div>';try{const r=await fetch(`${API}/api/properties/${id}/?_=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(r.status);const p=await r.json(),imgs=(p.images||[]).map(x=>mediaUrl(x.image)).filter(Boolean),main=imgs[0]||'',side=imgs.slice(1,3),district=p.district?.name||p.district_name||'';const facts=[fact(lang==='ru'?'Площадь':lang==='hy'?'Մակերես':'Area',p.area_sqm?`${p.area_sqm} m²`:''),fact(lang==='ru'?'Комнаты':lang==='hy'?'Սենյակներ':'Rooms',p.rooms),fact(lang==='ru'?'Спальни':lang==='hy'?'Ննջարաններ':'Bedrooms',p.bedrooms),fact(lang==='ru'?'Этаж':lang==='hy'?'Հարկ':'Floor',p.floor?`${p.floor}${p.total_floors?'/'+p.total_floors:''}`:''),fact(lang==='ru'?'Тип':lang==='hy'?'Տեսակ':'Type',p.property_type)].join('');$('#detailContent').innerHTML=`<div class="detail-gallery"><div class="main">${main?`<img src="${esc(main)}" alt="">`:`<div class="fallback">Narion</div>`}</div><div class="sidepics">${side.map(x=>`<img src="${esc(x)}" alt="">`).join('')||'<div class="fallback">Narion</div><div class="fallback">Narion</div>'}</div></div><div class="detail-body"><div><h2>${esc(titleOf(p))}</h2><div style="color:var(--muted)">${esc([district,p.address].filter(Boolean).join(' · '))}</div><div class="detail-price">${esc(money(p))}</div><div class="facts">${facts}</div>${descOf(p)?`<h3>${tr('description')}</h3><div class="desc">${esc(descOf(p))}</div>`:''}${p.videos?.length?`<h3 style="margin-top:26px">Narion POV™</h3><video controls playsinline style="width:100%;border-radius:16px" src="${esc(mediaUrl(p.videos[0].video))}"></video>`:''}</div><aside class="contact-card"><h3>${tr('request')}</h3><form id="inquiryForm"><div class="field"><label>${tr('name')}</label><input id="inqName" required></div><div class="field"><label>${tr('phone')}</label><input id="inqPhone" required></div><div class="field"><label>Email</label><input id="inqEmail" type="email"></div><div class="field"><label>${tr('message')}</label><textarea id="inqMsg"></textarea></div><button class="btn green" style="width:100%">${tr('send')}</button><div class="form-msg" id="inqStatus"></div></form></aside></div>`;$('#inquiryForm').onsubmit=e=>sendInquiry(e,p.id)}catch{$('#detailContent').innerHTML=`<div class="empty" style="margin:60px">${tr('loadingError')}</div>`}}
async function postInquiry(body,statusEl,successText){statusEl.textContent='…';try{const r=await fetch(`${API}/api/inquiries/`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error(await r.text());statusEl.textContent=successText;return true}catch{statusEl.textContent=lang==='ru'?'Не удалось отправить. Попробуйте ещё раз.':lang==='hy'?'Չհաջողվեց ուղարկել։ Փորձեք կրկին։':'Could not send. Please try again.';return false}}
async function sendInquiry(e,id){e.preventDefault();const ok=await postInquiry({property:Number(id),name:$('#inqName').value.trim(),phone:$('#inqPhone').value.trim(),email:$('#inqEmail').value.trim(),message:$('#inqMsg').value.trim()},$('#inqStatus'),tr('sent'));if(ok)e.target.reset()}
async function sendSeller(e){e.preventDefault();const details=$('#sellerMsg').value.trim();const body={name:$('#sellerName').value.trim(),phone:$('#sellerPhone').value.trim(),email:$('#sellerEmail').value.trim(),message:`SELLER LISTING REQUEST\n${details}`};const ok=await postInquiry(body,$('#sellerStatus'),tr('sellerSent'));if(ok)e.target.reset()}
function openModal(id){$('#'+id).classList.add('open')}function closeModal(id){$('#'+id).classList.remove('open')}
function authUser(){try{return JSON.parse(localStorage.getItem('narion_user')||'null')}catch{return null}}
function updateAuthUI(){const u=authUser();$('#loginBtn').style.display=u?'none':'';$('#userPill').style.display=u?'inline-block':'none';$('#userPill').textContent=u?(u.name||u.email):''}
function setAuthMode(mode){authMode=mode;$('#tabLogin').classList.toggle('active',mode==='login');$('#tabRegister').classList.toggle('active',mode==='register');$('#nameField').style.display=mode==='register'?'grid':'none';$('#authSubmit').textContent=mode==='login'?tr('login'):tr('register');$('#authMsg').textContent=''}
async function submitAuth(e){e.preventDefault();const msg=$('#authMsg');msg.textContent='…';const email=$('#authEmail').value.trim(),password=$('#authPassword').value,body=authMode==='register'?{email,password,name:$('#authName').value.trim()}:{email,password};try{const r=await fetch(`${API}/api/auth/${authMode==='register'?'register':'login'}/`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.detail||Object.values(data).flat().join(' '));localStorage.setItem('narion_token',data.token);localStorage.setItem('narion_user',JSON.stringify(data.user));updateAuthUI();closeModal('authModal');e.target.reset()}catch(err){msg.textContent=err.message}}
function logout(){localStorage.removeItem('narion_token');localStorage.removeItem('narion_user');updateAuthUI()}
function initMap(){map=L.map('map',{scrollWheelZoom:false}).setView([40.1772,44.5035],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);loadMapPoints()}
async function loadMapPoints(){try{const r=await fetch(`${API}/api/properties/map/?_=${Date.now()}`,{cache:'no-store'});const pts=await r.json();(Array.isArray(pts)?pts:[]).forEach(p=>{if(!Number.isFinite(Number(p.latitude))||!Number.isFinite(Number(p.longitude)))return;L.marker([p.latitude,p.longitude]).addTo(map).bindPopup(`<div class="map-popup"><strong>${esc(titleOf(p))}</strong><span>${esc(money(p))}</span><br><button style="margin-top:8px" onclick="openProperty(${Number(p.id)})">${tr('view')}</button></div>`)})}catch{}}
$$('.langs button').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;applyLang()});$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderListings()});
$('#searchBtn').onclick=()=>{query=$('#searchInput').value.trim();renderListings();$('#listings').scrollIntoView()};$('#searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#searchBtn').click()});$$('.chip').forEach(c=>c.onclick=()=>{$('#searchInput').value=c.dataset.q;$('#searchBtn').click()});$('[data-rent-link]').onclick=()=>{filter='rent';$$('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='rent'));setTimeout(renderListings,0)};
$('#loginBtn').onclick=()=>{setAuthMode('login');openModal('authModal')};$('#listBtn').onclick=()=>openModal('sellerModal');$('#sellerCta').onclick=()=>openModal('sellerModal');$('#tabLogin').onclick=()=>setAuthMode('login');$('#tabRegister').onclick=()=>setAuthMode('register');$('#authForm').onsubmit=submitAuth;$('#sellerForm').onsubmit=sendSeller;$('#userPill').onclick=()=>{if(confirm(tr('logout')+'?'))logout()};$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));
applyLang();loadListings();initMap();
