(()=>{
const COPY={
  hy:{buy:'Գնել',rent:'Վարձակալել',approach:'Մեր մոտեցումը',map:'Քարտեզ',login:'Մուտք',list:'Վաճառել գույքը',eyebrow:'NARION · ԱՆՇԱՐԺ ԳՈՒՅՔ · ՀԱՅԱՍՏԱՆ',heroTitle:'Գտեք ոչ թե պարզապես տուն, այլ ձեր տեղը Հայաստանում։',heroSub:'Ընտրված գույքեր՝ իրական լուսանկարներով, հստակ տվյալներով և անհատական ուղեկցմամբ՝ առաջին դիտումից մինչև որոշում։',explore:'Բացահայտել գույքերը',sellProperty:'Վաճառել գույքը',search:'Փնտրել',searchPh:'Որտե՞ղ եք ցանկանում ապրել',apartments:'Բնակարաններ',privateService:'ԱՆՀԱՏԱԿԱՆ ՍՊԱՍԱՐԿՈՒՄ',proofTitle:'Ընտրեք վստահությամբ',proof1:'Իրական լուսանկարներ և ամբողջական տվյալներ',proof2:'Գույքի մանրամասները՝ մեկ էջում',proof3:'Դիտման հայտ՝ անմիջապես Narion-ին',discover:'ԲԱՑԱՀԱՅՏԵԼ',promiseTitle:'Անշարժ գույքի ընտրություն՝ ավելի բարձր չափանիշով։',promiseText:'Narion-ում յուրաքանչյուր գույք պետք է լինի հասկանալի, գեղեցիկ ներկայացված և հեշտ համեմատելի։ Մենք նվազեցնում ենք ավելորդ աղմուկը, որպեսզի դուք կենտրոնանաք ամենակարևորի վրա՝ ճիշտ որոշման։',serviceBuy:'Գտնել ձեր տունը',serviceBuyText:'Ընտրված առաջարկներ՝ բնակվելու, ներդրման կամ նոր սկզբի համար։',serviceNew:'Նորակառույցներ',serviceNewText:'Ժամանակակից նախագծեր՝ հստակ տվյալներով և մեկ վայրում։',serviceSell:'Ներկայացնել ձեր գույքը',serviceSellText:'Պրոֆեսիոնալ ներկայացում և անմիջական կապ հետաքրքրված գնորդների հետ։',catalog:'Ընտրված առաջարկներ',catalogTitle:'Գույքեր, որոնց արժե ուշադրություն դարձնել',catalogSub:'Միայն հրապարակված Narion գույքեր՝ իրական լուսանկարներով և արդիական մանրամասներով։',all:'Բոլորը',newbuild:'Նորակառույց',why:'Ինչու Narion',whyTitle:'Քիչ աղմուկ։ Ավելի շատ վստահություն։',whyIntro:'Լավ գործարքը սկսվում է ոչ թե բազմաթիվ հայտարարություններից, այլ ճիշտ տեղեկատվությունից և պարզ հաջորդ քայլից։',trust1t:'Ընտրված ներկայացում',trust1d:'Գույքերը ներկայացվում են պարզ, ամբողջական և առանց ավելորդ խճճվածության։',trust2t:'Ամեն ինչ՝ մեկ էջում',trust2d:'Լուսանկարներ, գին, մակերես, սենյակներ, հարկ, նկարագրություն և քարտեզ։',trust3t:'Անմիջական հաջորդ քայլ',trust3d:'Հավանեցիք գույքը՝ ուղարկեք դիտման հայտ և շարունակեք Narion-ի հետ։',editorialTitle:'Տուն ընտրելը թվերից ավելին է։ Դա զգացողություն է, միջավայր և ապագայի պատկերացում։',editorialText:'Մենք ուզում ենք, որ յուրաքանչյուր այց Narion սկսվի հետաքրքրությամբ և ավարտվի վստահությամբ՝ առանց ավելորդ ճնշման ու բարդության։',mapTitle:'Տեսեք գույքերը քաղաքի համատեքստում',mapSub:'Գտեք գույքը ոչ միայն նկարով, այլ նաև այն միջավայրով, որտեղ այն գտնվում է։',owners:'ԳՈՒՅՔԻ ՍԵՓԱԿԱՆԱՏԵՐԵՐԻՆ',sellTitle:'Ձեր գույքն արժանի է ճիշտ ներկայացման։',sellSub:'Պատմեք մեզ ձեր գույքի մասին։ Մենք կստանանք տվյալները և կկապվենք՝ ներկայացման ու հաջորդ քայլերի համար։',start:'Ներկայացնել գույքը',footer:'Անշարժ գույք Հայաստանում՝ ժամանակակից ներկայացմամբ և մարդկային մոտեցմամբ։',sellerTitle:'Ներկայացնել գույքը',sellerText:'Թողեք ձեր կոնտակտները և համառոտ նկարագրեք գույքը։ Մենք կկապվենք ձեզ հետ։'},
  ru:{buy:'Купить',rent:'Арендовать',approach:'Наш подход',map:'Карта',login:'Войти',list:'Продать объект',eyebrow:'NARION · НЕДВИЖИМОСТЬ · АРМЕНИЯ',heroTitle:'Найдите не просто дом, а своё место в Армении.',heroSub:'Отобранные объекты, реальные фотографии, понятные данные и персональное сопровождение — от первого просмотра до решения.',explore:'Смотреть объекты',sellProperty:'Продать объект',search:'Найти',searchPh:'Где вы хотите жить?',apartments:'Квартиры',privateService:'ПЕРСОНАЛЬНЫЙ СЕРВИС',proofTitle:'Выбирайте уверенно',proof1:'Реальные фотографии и полная информация',proof2:'Все детали объекта на одной странице',proof3:'Заявка на просмотр напрямую в Narion',discover:'СМОТРЕТЬ ДАЛЬШЕ',promiseTitle:'Выбор недвижимости по более высокому стандарту.',promiseText:'В Narion каждый объект должен быть понятным, красиво представленным и удобным для сравнения. Мы убираем лишний шум, чтобы вы сосредоточились на главном — правильном решении.',serviceBuy:'Найти свой дом',serviceBuyText:'Отобранные предложения для жизни, инвестиций или нового начала.',serviceNew:'Новостройки',serviceNewText:'Современные проекты с понятными данными в одном месте.',serviceSell:'Представить свой объект',serviceSellText:'Профессиональная подача и прямой контакт с заинтересованными покупателями.',catalog:'Избранные предложения',catalogTitle:'Объекты, на которые стоит обратить внимание',catalogSub:'Только опубликованные объекты Narion — с реальными фотографиями и актуальными деталями.',all:'Все',newbuild:'Новостройки',why:'Почему Narion',whyTitle:'Меньше шума. Больше уверенности.',whyIntro:'Хорошая сделка начинается не с количества объявлений, а с правильной информации и понятного следующего шага.',trust1t:'Отобранная подача',trust1d:'Объекты представлены ясно, полно и без лишней сложности.',trust2t:'Всё на одной странице',trust2d:'Фото, цена, площадь, комнаты, этаж, описание и карта.',trust3t:'Понятный следующий шаг',trust3d:'Понравился объект — отправьте заявку на просмотр и продолжите с Narion.',editorialTitle:'Выбор дома — это больше, чем цифры. Это ощущение, среда и образ будущего.',editorialText:'Мы хотим, чтобы каждый визит в Narion начинался с интереса и заканчивался уверенностью — без лишнего давления и сложности.',mapTitle:'Смотрите объекты в контексте города',mapSub:'Выбирайте недвижимость не только по фотографии, но и по окружению, в котором она находится.',owners:'ДЛЯ СОБСТВЕННИКОВ',sellTitle:'Ваш объект заслуживает правильной презентации.',sellSub:'Расскажите нам об объекте. Мы получим данные и свяжемся с вами по поводу презентации и следующих шагов.',start:'Представить объект',footer:'Недвижимость в Армении — современная подача и человеческий подход.',sellerTitle:'Представить объект',sellerText:'Оставьте контакты и кратко опишите объект. Мы свяжемся с вами.'},
  en:{buy:'Buy',rent:'Rent',approach:'Our approach',map:'Map',login:'Log in',list:'Sell a property',eyebrow:'NARION · REAL ESTATE · ARMENIA',heroTitle:'Find more than a home. Find your place in Armenia.',heroSub:'Curated properties, authentic photography, clear information and personal guidance — from first viewing to decision.',explore:'Explore properties',sellProperty:'Sell a property',search:'Search',searchPh:'Where would you like to live?',apartments:'Apartments',privateService:'PERSONAL SERVICE',proofTitle:'Choose with confidence',proof1:'Authentic photography and complete information',proof2:'Every property detail in one place',proof3:'Viewing requests go directly to Narion',discover:'DISCOVER',promiseTitle:'A higher standard for choosing real estate.',promiseText:'Every Narion property should be clear, beautifully presented and easy to compare. We reduce the noise so you can focus on what matters most — the right decision.',serviceBuy:'Find your home',serviceBuyText:'Curated opportunities for living, investing or a new beginning.',serviceNew:'New developments',serviceNewText:'Modern projects with clear information in one place.',serviceSell:'Present your property',serviceSellText:'Professional presentation and direct contact with interested buyers.',catalog:'Selected properties',catalogTitle:'Properties worth your attention',catalogSub:'Only published Narion listings with authentic photography and up-to-date details.',all:'All',newbuild:'New builds',why:'Why Narion',whyTitle:'Less noise. More confidence.',whyIntro:'A good transaction starts not with more listings, but with better information and a clear next step.',trust1t:'Curated presentation',trust1d:'Properties are presented clearly, completely and without unnecessary complexity.',trust2t:'Everything in one place',trust2d:'Photos, price, area, rooms, floor, description and map.',trust3t:'A clear next step',trust3d:'Found a property you like? Send a viewing request and continue with Narion.',editorialTitle:'Choosing a home is more than numbers. It is a feeling, an environment and a vision of the future.',editorialText:'We want every visit to Narion to begin with curiosity and end with confidence — without unnecessary pressure or complexity.',mapTitle:'See properties in the context of the city',mapSub:'Choose not only by the property itself, but by the environment around it.',owners:'FOR PROPERTY OWNERS',sellTitle:'Your property deserves the right presentation.',sellSub:'Tell us about your property. We will review the details and contact you about presentation and next steps.',start:'Present your property',footer:'Real estate in Armenia with modern presentation and a human approach.',sellerTitle:'Present your property',sellerText:'Leave your contact details and briefly describe the property. We will get in touch.'}
};

function activeLang(){return document.querySelector('.langs button.active')?.dataset.lang || localStorage.getItem('narion_lang') || 'hy'}
function applyCopy(lang){const c=COPY[lang]||COPY.hy;document.documentElement.lang=lang==='hy'?'hy':lang;document.querySelectorAll('[data-t]').forEach(el=>{const k=el.dataset.t;if(c[k])el.textContent=c[k]});document.querySelectorAll('[data-ph]').forEach(el=>{const k=el.dataset.ph;if(c[k])el.placeholder=c[k]})}

function wireSeller(id){const el=document.getElementById(id);if(!el)return;el.addEventListener('click',e=>{e.preventDefault();document.getElementById('sellerCta')?.click();document.getElementById('mobileMenu')?.classList.remove('open');document.body.classList.remove('menu-open')})}

const header=document.getElementById('siteHeader');const onScroll=()=>header?.classList.toggle('scrolled',window.scrollY>24);onScroll();window.addEventListener('scroll',onScroll,{passive:true});

const menuBtn=document.getElementById('menuBtn'),menu=document.getElementById('mobileMenu');menuBtn?.addEventListener('click',()=>{const open=!menu.classList.contains('open');menu.classList.toggle('open',open);document.body.classList.toggle('menu-open',open);menuBtn.classList.toggle('open',open)});menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');document.body.classList.remove('menu-open')}));

wireSeller('heroSeller');wireSeller('serviceSeller');wireSeller('mobileSeller');

const video=document.getElementById('heroVideo'),toggle=document.getElementById('videoToggle');toggle?.addEventListener('click',()=>{if(!video)return;if(video.paused){video.play();toggle.textContent='Ⅱ';toggle.setAttribute('aria-label','Դադարեցնել տեսանյութը')}else{video.pause();toggle.textContent='▶';toggle.setAttribute('aria-label','Միացնել տեսանյութը')}});

const io=('IntersectionObserver'in window)?new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');io.unobserve(e.target)}}),{threshold:.12}):null;document.querySelectorAll('.reveal').forEach(el=>io?io.observe(el):el.classList.add('in-view'));

applyCopy(activeLang());document.querySelectorAll('.langs button').forEach(btn=>btn.addEventListener('click',()=>setTimeout(()=>applyCopy(btn.dataset.lang),0)));
})();